QUANT_DATA_TYPE: log2 FC

DOTPLOTS: True

MIN_NUM_GENES: 5

MAX_DCNT: 50
MIN_LEVEL: 3

TT_OVERLAP_MEASURE: OC
MIN_WEIGHT_TT_EDGE: 0.5

SC_BC_OVERLAP_MEASURE: OC
MIN_WEIGHT_SC_BC: 0.25

BC_BC_OVERLAP_MEASURE: J
MIN_WEIGHT_BC_BC: 0.1

MAX_CLUSTER_SIZE_THRESH: 15
MAX_META_COMMUNITY_SIZE_THRESH: 15

COMBINE_TERM_TYPES: False

HEATMAP_WIDTH_MIN: 10
HEATMAP_HEIGHT_MIN: 5

HEATMAP_MIN: -4
HEATMAP_MAX: 4

SEARCH_WORDS:
- search 1
- search 2
- search 3

GENE_INDEX: 7
QD_INDEX: 2

MSIGDB_HTML:
OBO_FILE:

EA_FILE:
