QUANT_DATA_TYPE: log2 FC
# This is the label for the colourmap legend in the split heatmaps

DOTPLOTS: True
# Set this to True if you want GeneFEAST to generate dot plots of your functional enrichment analysis (FEA) results.
# IMPORTANT: If this is set to True then fields GeneRatio. BgRatio, p.adjust and count are required in the FEA results file

MIN_NUM_GENES: 5
# Number of genes of interest that a term must annotate in order to be included in the GeneFEAST report.

MAX_DCNT: 50
MIN_LEVEL: 3
# These parameters pertain to GO terms. 
# MAX_DCNT means maximum descendant count allowed for a GO term to be included in the GeneFEAST summary report.
# MIN_LEVEL means the minimum level in the GO hierarchy that GO term must have to be included in the GeneFEAST summary report.
# Please refer to article https://doi.org/10.1038/s41598-018-28948-z for further explanation of these terms.

TT_OVERLAP_MEASURE: OC
# Overlap measure to use when calculating the gene set overlap between terms. Two values are recognised:
# OC (Overlap Coefficient)
# J (Jaccard Index)
# We recommend using OC here.
MIN_WEIGHT_TT_EDGE: 0.5
# Minimum gene set overlap between terms (as measured using TT_OVERLAP_MEASURE) required for two terms to be
# connected (i.e. to have an edge between them) in the term-term network that GeneFEAST constructs prior to finding
# communities of terms. (Please see GeneFEAST paper for further details).

SC_BC_OVERLAP_MEASURE: OC
# Overlap measure to use when calculating the gene set overlap between a term and a community of terms. Two values are recognised:
# OC (Overlap Coefficient)
# J (Jaccard Index)
# We recommend using OC here.
MIN_WEIGHT_SC_BC: 0.25
# Minimum gene set overlap required between a term and a community of terms for that term to be considered weakly connected
# to the community of terms (i.e. having some connectivtity to the community, but not enough to be considered part of that community).

BC_BC_OVERLAP_MEASURE: J
MIN_WEIGHT_BC_BC: 0.1
# Overlap measure to use when calculating the gene set overlap between two communities of terms. Two values are recognised:
# OC (Overlap Coefficient)
# J (Jaccard Index)
MIN_WEIGHT_SC_BC: 0.25
# Minimum gene set overlap required between two communities of terms for those two communities to be connected (i.e. to 
# have an edge between them) in the community-community network that GeneFEAST constructs prior to finding
# meta-communities of communities. (Please see GeneFEAST paper for further details).

MAX_CLUSTER_SIZE_THRESH: 15
MAX_META_COMMUNITY_SIZE_THRESH: 15

COMBINE_TERM_TYPES: False

HEATMAP_WIDTH_MIN: 10
HEATMAP_HEIGHT_MIN: 5

HEATMAP_MIN: -4
HEATMAP_MAX: 4

SEARCH_WORDS:
- search 1
- search 2
- search 3

GENE_INDEX: 7
QD_INDEX: 2

MSIGDB_HTML:
OBO_FILE:

EA_FILE:
